# Use postgres/example user/password credentials
version: '3.1'

services:

  paastis-registry:
    container_name: "paastis-registry"
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

#  paastis-db:
#    container_name: "paastis-db"
#    image: postgres
#    restart: always
#    ports:
#      - 2345:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: example
#      POSTGRES_DB: paastis

volumes:
  cache:
