# Use postgres/example user/password credentials
version: '3.1'

services:

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  db:
    image: postgres
    restart: always
    container_name: paastis_db
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: paastis

  adminer:
    image: adminer
    restart: always
    container_name: paastis_adminer
    ports:
      - 2346:8080

volumes:
  cache:
